Add Tooltip
js-tasks-ru/htmlcss-20241107_natalya79 pull request #10
Opened 2024-12-04 12:22 UTC by TashaSlon

2024-12-04 12:22 UTC, jsru-1 commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2024-12-04 23:08 UTC, GSemikozov requested changes

2024-12-04 23:08 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 70px;
ни в коем случае) удаляем

2024-12-04 23:08 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    top: -185%;
`bottom: calc(100% + 10px)`

2024-12-05 03:51 UTC, TashaSlon commented on 05-lection3/01-tooltip/tooltip.css
> +    top: -185%;
Поменяла

2024-12-05 03:52 UTC, TashaSlon commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 70px;
Убрала. Но как тогда проверять, что тултип появляется?))

2024-12-12 14:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 70px;
на body написать style="margin-top: 100px" :)

2024-12-12 14:58 UTC, GSemikozov commented on 05-lection3/01-tooltip/tooltip.css
> +    margin: 70px;
@TashaSlon

2024-12-12 14:58 UTC, GSemikozov approved these changes

2024-12-12 14:59 UTC, merged